SatelliteQE/manifester

.gitignore, .pre-commit-config.yaml, README.md, logs/.gitignore, manifester/__init__.py, manifester/commands.py, manifester/helpers.py, manifester/logger.py, manifester/manifester.py, manifester/settings.py, manifester_settings.yaml.example, setup.cfg, setup.py
Provide baseline functionality for Manifester.
=> Add initial content

.flake8, Dockerfile, manifester/logger.py, manifester/settings.py
This commit introduces a Dockerfile for container image builds.
Additionally, fixed some small items and added a more permissive flake
config
=> Add Dockerfile

.github/workflows/python-publish.yml
This action uses a different way of specifying the version, so updating it to the correct way.
=> Update pypi-publish to correct version

manifester/manifester.py, manifester/settings.py
This commit adds a method to the Manifester class that performs all
steps necessary to return a manifest archive based on
manifester_settings.yaml. This should enable Robottelo
tests/fixtures/helpers to instantiate a Manifester object and
subsequently generate a manifest with a single method call. I have
tested this in the test_positive_create test in
tests/foreman/api/test_subscription.py, and the test passed:
```
org = entities.Organization().create()
manifester = Manifester(manifest_category='golden_ticket')
with manifester.get_manifest() as manifest:
upload_manifest(org.id, manifest.content)
```
This PR also implements Dynaconf validators for manifester settings,
which were previously commented out.
=> Add get_manifest method to Manifester object

README.md, manifester/commands.py, manifester/helpers.py, manifester/manifester.py, manifester/settings.py, manifester_settings.yaml.example
Previously, API URLs were hardcoded in the body of
manifester/manifester.py, and the offline token (which is used to
generate an access token, which is in turn used to authenticate API
calls) was a top-level setting. This commit makes the offline_token
setting a child setting of each manifest_category, and it moves the API
URLs to the settings file, also as children of each manifest_category.
This should enable greater flexibility by letting users associate
manifests with multiple RHSM accounts (potentially in multiple
environments, such as Red Hat's staging environment) in a single
settings file.
This commit also makes numerous formatting changes as a result of
running pre-commit.
Additionally, the offline_token validator in manifester/settings.py has
been commented out as it fails to …
=> Refactor settings and reformat multiple files

manifester/manifester.py
This commit adds a new method to the manifester class,
delete_subscription_allocation. This is necessary to prevent a buildup
of subscription allocations in RHSM accounts and to ensure that
subscriptions are not consumed by subscription allocations after those
allocations are no longer needed. Note that the first step in this
method is `self._access_token = None` because access tokens are only
valid for 5 minutes. Since it is likely that allocations will need to be
deleted more than five minutes after they are created, this step ensures
that a fresh, valid access token is passed with the DELETE request.
=> Add delete method to Manifester class

manifester/manifester.py
This change adds a basic content manager that creates the manifest on enter and deletes the allocation on exit.
This can certainly be beefed up!
=> Add basic context manager functionality

manifester/manifester.py
This PR modifies settings.py to accept configuration files beyond
manifester_settings.yaml as input via the FRAMEWORK_DIRECTORY
environment variable. This change assumes that those additional
configuration files will be in yaml format and that all configuration
files in the framework directory should be ingested, but I am open to
modifying this implementation if it seems too Robottelo-centric.
=> Add support for external configuration

manifester/manifester.py
The `rhsatqe` RHSM account contains a pool of Red Hat Beta Access
subscriptions with an unlimited quantity. Because this quantity is
represented as `-1` in the response to an API request for the details of
that pool, Manifester previously failed to add subscriptions from that
pool to the allocations it was creating. This PR enables Manifester to
pull entitlements from subscription pools that contain an unlimited
quantity of entitlements.
=> Allow adding entitlements from unlimited pools

manifester/manifester.py
Robottelo's CLI subscription upload method requires copying the manifest
to the Satellite's file system before the upload can be performed. This
PR adds the local relative path to the manifest and the filename of the
manifest as instance attributes of the returned manifest object to
facilitate these operations.
=> Add path and filename as attributes of manifest

manifester/helpers.py, manifester/manifester.py
When creating a subscription allocation, the RHSM API only accepts a string in the form of `sat-X.Y` for the `sat_version` parameter. This PR adds a helper function that will remove the Z-stream version if it is included in the value of the `sat_version` setting. It also adds error handling for errors caused by an invalid `sat_version` during subscription allocation creation.
=> Sanitize sat_version and handle sat_version errors

manifester/manifester.py
The RHSM API does not support disabling Simple Content Access (SCA) on subscription allocations at creation time. This PR adds a check after creating an allocation and, if SCA is disabled in the settings for that allocation, performs another API call to disable SCA on that allocation. The endpoint for disabling SCA requires that the `simpleContentAccess` parameter be passed as JSON data rather than as a URL parameter, hence the use of the `json` parameter where other requests in Manifester use `params`.
=> Disable SCA after creating allocation

manifester/manifester.py
In some scenarios, it will be useful to have the filename of the manifest archive immediately accessible as an attribute of the object returned by manifester. This PR assigns a manifest name based on the subscription allocation name to the Manifester object during instantiation and subsequently assigns that name to the response object containing the manifest returned by the API's export job.
=> Add manifest filename as attribute

manifester/helpers.py
Previously, the `process_sat_version` helper method assumed that all Satellite versions would be in the form of X.Y.Z. The most recent release of Satellite 6.11, though, is 6.11.4.1, which demonstrates that this assumption is not valid in all cases. This PR modifies the helper method to account for cases where the Satellite version has more digits than X.Y.Z.
=> Fix inability to process long sat_versions

manifester/helpers.py
With the adoption of Satellite stream, the logic for selecting a sat_version for subscription allocations created by manifester is no longer valid in all cases. This PR modifies the logic to default to the most recent valid version if initial processing of the provided sat_version does not yield a valid version.
=> Fail over to the latest valid sat_version

.github/workflows/codeql-analysis.yml, manifester/logger.py
This should hopefully solve the issue we're seeing with missing log file path in robottelo's github checks. Though I'm a but dubious as to why the GHA isn't using robottelo's own logs directory..
Also added a call to manifester's cli since no unit tests are currently being ran in checks.
=> Added in directory creation for logging path

manifester/manifester.py, manifester/settings.py, manifester_settings.yaml.example
This pull request is part of an effort to implement an inventory system for subscription allocations created by Manifester. In situations where multiple different users are creating allocations using the same login on a shared RHSM account, the RHSM API does not provide a means to differentiate which allocations were created by which users. To facilitate such differentiation, this PR adds a `username_prefix` setting that is used in the construction of the allocation name. This should enable syncing the allocations created by individual users to their local inventories while avoiding collisions with allocations created by other users.
=> Add username_prefix to settings and allocation name

manifester/helpers.py, manifester/manifester.py, manifester_settings.yaml.example, tests/test_manifester.py
This PR adds helper functions to load a local inventory file and to replace the contents of that file. It also adds calls to the update inventory method several times in the course of a manifester run to try to avoid stale data being stored persistently in the inventory file in the event that a manifester run terminates unexpectedly.
=> Add basic inventory file management

manifester/commands.py, manifester/helpers.py, manifester/manifester.py, tests/test_manifester.py
This PR is another step in the manifester inventory/CLI improvement effort. It adds functionality to and testing for the CLI with the goal of making Manifester useful for interactive users in addition to its current primary usecase in automated workflows.
=> Improve CLI functionality and CLI tests

manifester/logger.py, manifester/manifester.py
Currently, the manifester CLI writes debug-level log messages to the terminal regardless of the `log_level` setting. This PR imports and runs the `setup_logzero` function from manifester/logger.py to make the CLI write log messages at the level specified in the settings.
=> Make CLI respect log_level setting

manifester/manifester.py
As described here https://github.com/SatelliteQE/robottelo/pull/14405#discussion_r1526828098 this will make the uuid available
=> Make uuid available

manifester/helpers.py
This PR fixes an error that occurred when attempting to load the inventory while the inventory file is not present at the `inventory_path` location.
=> Create inventory file if absent when loading

.github/workflows/python-publish.yml
Manifester's build and publish workflow is failing on the `setup-python` action with the error `The version '3.1' with architecture 'x64' was not found for Ubuntu 22.04.` I am guessing that `3.10` is being interpreted as a float and evaluated to `3.1`. This PR converts the version to a string in the hope that this allows the version number to be evaluated accurately.
=> Fix syntax error in python-publish workflow

.github/workflows/python-publish.yml
Manifester's python-publish workflow has been failing during the Setup and Build step. These failures persisted after my previous PR fixing a syntax issue with the version. This PR switches from invoking `setup.py` directly to invoking the `build` tool in an attempt to resolve the error.
=> Use build command instead of setup.py

Makefile, manifester/commands.py, manifester/helpers.py, manifester/manifester.py, manifester/settings.py, manifester_settings.yaml.example, pyproject.toml, scripts/vault_login.py
A CI test failure in https://github.com/SatelliteQE/robottelo/pull/14633 revealed that Manifester was unable to interpolate secrets stored in HashiCorp Vault. This PR adds support for Vault secrets based on Robottelo's implementation of Vault integration.
=> Enable support for Vault secrets in Manifester

.github/workflows/codeql-analysis.yml, pyproject.toml
When I converted Manifester to pyproject.toml, I did not include a `project.scripts` section. As a result, an executable for the Manifester CLI is not installed when the Manifester package is installed. This PR adds a `project.scripts` section to pyproject.toml so the Manifester CLI is easily accessible.
=> Add `scripts` section to pyproject.toml

manifester/manifester.py
This PR greatly increases the number of times manifester will check the status of a manifest export job in RHSM before timing out. This is intended to address scenarios in which there is a significant gap between an export job being scheduled in RHSM and the job starting execution.
=> Increase export job check timeout

manifester/_settings.py, manifester/commands.py, manifester/helpers.py, manifester/logger.py, manifester/manifester.py, manifester/settings.py
Broker and Manifester both use the default logger, so the last to have their log setup run overrides the other.
This PR isolates the manifester's own logger in its library, but it keeps the possibility to modify the logger from outside using the `setup_logzero` API.
=> Isolate manifester's logger

manifester/commands.py, manifester/manifester.py
This PR modifies the inventory CLI command to accept an offline_token argument. This should resolve an issue with generating an access token that I'm encountering with a CI pipeline. With this change, the job can pass an environment variable containing the offline token to the Manifester CLI, which mirrors how we access the same token in another CI use case.
=> Add offline token argument to inventory command

manifester/commands.py
This PR makes a similar change to the change made in https://github.com/SatelliteQE/manifester/pull/45 but for the `manifester delete` subcommand. This is to support a CI usecase of the manifester CLI. The PR also reformats the `commands.py` module with Ruff.
=> Accept offline token option for CLI delete command

manifester/helpers.py
This PR modifies the API requests that fetch the list of subscription pools to include future-dated subscriptions when using a stage RHSM account while leaving requests to prod RHSM unchanged.
=> Return future-dated subscription pools from stage

manifester/helpers.py, manifester/settings.py, manifester_settings.yaml.example
We're seeing an issue where [fetch_paginated_data](https://github.com/SatelliteQE/manifester/blob/caa73e4ec8306c2c8406bb110648134215bf7ff7/manifester/helpers.py#L122) is failing on simple_retry with timeout error. This PR adds support to make max_timeout configurable to avoid this issue.
=> Make max_timeout var in simple_retry helper configurable
